//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.OrdenMecanico = new HashSet<OrdenMecanico>();
            this.OrdenRefaccion = new HashSet<OrdenRefaccion>();
        }
    
        public int Id { get; set; }
        public int Folio { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Equipo { get; set; }
        public string Observaciones { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> TipoPago { get; set; }
        public int Status { get; set; }
        public int IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenMecanico> OrdenMecanico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenRefaccion> OrdenRefaccion { get; set; }
    }
}
