//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenRefaccion
    {
        public int Id { get; set; }
        public int IdOrden { get; set; }
        public int IdRefaccion { get; set; }
        public decimal PrecioUnitario { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Orden Orden { get; set; }
        public virtual Refaccion Refaccion { get; set; }
    }
}
